const type = {
  0x80: 'Number of data bytes',
  0x81: 'Number of data bytes',
  0x82: 'File descriptor',
  0x83: 'File identifier',
  0x84: 'DF name',
  0x85: 'Proprietary information',
  0x86: 'Security attributes in proprietary format',
  0x87: 'FCI extensions EF identifier',
  0x88: 'Short EF identifier',
  0x8a: 'Life cycle status',
  0x8b: 'Security attribute in extended format',
  0x8c: 'Security attribute in compact format, SE oriented',
  0x8d: 'Identifier of an EF containing SE templates',
  0x8e: 'Logical channel security attribute',
  0x8f: 'Profile indicator',
  0x92: 'Data descriptor',
  0x96: 'as defined in ISO/IEC 7816-11',
  0x97: 'DF list',
  0x98: 'Instance number',
  0x99: 'Number of DOs in the current template after file or DO selection',
  0x9a: 'Number of EFs within a DF',
  0x9b: 'EF list',
  0x9c: 'Security attribute in compact format, SPT oriented',
  0x9d: 'Tag of the DO(s) to which DO\'62\' applies',
  0xa0: 'Security attribute template for DOs',
  0xa1: 'Security attribute template in proprietary format',
  0xa2: 'TODO',
  0xa3: 'Interface and LCS dependent security attribute template',
  0xa5: 'Proprietary information encoded in BER-TLV',
  0xa6: 'as defined in ISO/IEC 7816-11',
  0xab: 'Security attribute template in expanded format',
  0xac: 'Cryptographic mechanism identifier template',
  0xad: 'Security parameters template',
  0xaf: 'Template encapsulating one or more DO\'06\' (OID) relevant to the application',
};

module.exports = type;
